apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-server
  namespace: prometheus
spec:
  podSelector:
    matchLabels:
      app: prometheus-server
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: prometheus

